---

sudo: required

services:
  - docker

before_install:
  # Update the host with latest versions
  - sudo apt-get update -qq

install:
  # Install Ansible on host
  - pip install ansible --user

  # Install version 1.9 of docker-py, later versions fail version checking
  - pip install docker-py==1.9.0 --user

  # Add ansible.cfg to pick up roles path.
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

  # Pull a CentOS image with systemd installed for the Docker containers
  - docker pull centos/systemd

script:
  # Install dependent roles 
  - ansible-galaxy install sleighzy.zookeeper

  # Check syntax of Ansible role
  - ansible-playbook tests/test.yaml -i tests/inventory --syntax-check

  # Run Ansible role
  - ansible-playbook tests/test.yaml -i tests/inventory --verbose

  # Run the playbook and role again to ensure that it is idempotent and nothing has changed
  - >
    ansible-playbook tests/test.yaml -i tests/inventory --verbose
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Check that the ZooKeeper service is running
  - >
    docker exec server-1 systemctl status zookeeper 2>&1
    | awk 'FNR == 3 {print}' | grep "active (running)"
    && (echo "Service running - pass" && exit 0)
    || (echo "Service running - fail" && exit 1)
  
  - >
    docker exec server-2 systemctl status zookeeper 2>&1
    | awk 'FNR == 3 {print}' | grep "active (running)"
    && (echo "Service running - pass" && exit 0)
    || (echo "Service running - fail" && exit 1)
  
  - >
    docker exec server-3 systemctl status zookeeper 2>&1
    | awk 'FNR == 3 {print}' | grep "active (running)"
    && (echo "Service running - pass" && exit 0)
    || (echo "Service running - fail" && exit 1)

  # Check that a Znode can be successfully created
  - >
    docker exec server-1 /usr/share/zookeeper/bin/zkCli.sh create /TestZnode1 "test-node-1" 2>&1
    | awk -F\" '/Created/ {print $1}' | grep "Created"
    && (echo "Znode ceate test - pass" && exit 0)
    || (echo "Znode create test - fail" && exit 1)

  # Check that the Znode is available on all nodes in the cluster
  - >
    docker exec server-2 /usr/share/zookeeper/bin/zkCli.sh ls /TestZnode1 2>&1
    | awk 'END{print}' | grep 'Node does not exist'
    && (echo "Znode cluster ceate test - fail" && exit 1)
    || (echo "Znode cluster create test - pass" && exit 0)
  - >
    docker exec server-3 /usr/share/zookeeper/bin/zkCli.sh ls /TestZnode1 2>&1
    | awk 'END{print}' | grep 'Node does not exist'
    && (echo "Znode cluster ceate test - fail" && exit 1)
    || (echo "Znode cluster create test - pass" && exit 0)

  # Check that the Solr service is running
  - >
    docker exec server-1 systemctl status solr 2>&1
    | awk 'FNR == 3 {print}' | grep "active (running)"
    && (echo "Service running - pass" && exit 0)
    || (echo "Service running - fail" && exit 1)

after_script:
  # Stop and remove the Docker containers
  - docker stop server-1 && docker rm server-1
  - docker stop server-2 && docker rm server-2
  - docker stop server-3 && docker rm server-3

  # Remove the Docker network
  - docker network rm zookeeper

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
